### ISSUE TITLE
Issue with animations / example notebook

### ISSUE THREAD

**Issue by haesleinhuepf** [guiwitz/microfilm#18]
Hi @guiwitz ,

I'm continuing to explore microfilm and got stuck creating animations, I'm afraid recent changes broke the example in [this notebook](https://github.com/guiwitz/microfilm/blob/master/notebooks/create_animations.ipynb).

When calling this cell:
```
anim = Microanim(data=image, cmaps=['pure_blue','pure_red', 'pure_green'])
anim.ui
```

I receive this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [9], in <module>
----> 1 anim = Microanim(data=image, cmaps=['pure_blue','pure_red', 'pure_green'])
      2 anim.ui

File c:\structure\code\microfilm\microfilm\microanim.py:48, in Microanim.__init__(self, data, channels, cmaps, flip_map, rescale_type, limits, num_colors, proj_type, alpha, volume_proj, channel_names, channel_label_show, channel_label_type, channel_label_size, scalebar_thickness, scalebar_unit_per_pix, scalebar_size_in_units, unit, scalebar_location, scalebar_color, scalebar_font_size, scalebar_kwargs, scalebar_font_properties, ax, fig_scaling, dpi, label_text, label_location, label_color, label_font_size, label_kwargs, cmap_objects, show_colorbar, show_plot)
     46     target_dim=5 if (volume_proj is not None) else 3
     47     if data.ndim != target_dim:
---> 48         raise ValueError(f"The array needs {target_dim} dimensions, yours has {data.ndim}")
     49     data = Nparray(nparray=data)
     51 self.data = data

ValueError: The array needs 3 dimensions, yours has 4
```

And just a bit more context: I'm trying to turn a single-channel video (in dimension order TYX) into an animation... The error above however comes when running the unmodified notebook that uses a CTYX dataset...

Thanks!

Best,
Robert

**Comment by guiwitz** [comment]
Hi @haesleinhuepf,

thanks for catching this! My verification of the input dimensions which should take care of arrays with incorrect dimensions was just wrong. The input should indeed be 5D (volume) or 4D and not 3D. I fixed this and pushed it to pypi, so it should work now.

Cheers,

Guillaume

**Comment by haesleinhuepf** [comment]
Yes, it works. Thanks for the light speed response!
