### ISSUE TITLE
Saving a microanimation

### ISSUE THREAD

**Issue by puentene** [guiwitz/microfilm#23]
**Description:**
If the microanimation is saved in any format other than .gif I get the complaint even when no fps keyword is given: 
_TypeError: write() got an unexpected keyword argument 'fps'_

**used code that works fine with a .gif**

time = 1000
image405_movie = np.array([image405[1]]*image640.shape[0])
image488_movie = np.array([image488[1]]*image640.shape[0])
fake_multichannel_movie = np.array((image405_movie[:time,:,:], image640[:time,:,:], image488_movie[:time,:,:]))
microanim = Microanim(data=fake_multichannel_movie, cmaps=['pure_blue','pure_red', 'pure_green'], fig_scaling=5,
                      unit='um', scalebar_size_in_units=3, scalebar_unit_per_pix=0.065,
                      scalebar_thickness=0.02, scalebar_font_size=20)

microanim.add_label('A', label_font_size=30)
microanim.add_time_stamp('T', 10, location='lower left', timestamp_size=20)

microanim.save_movie(os.path.join(outfolder, os.path.split(file)[1][:-4] + '_composit.avi'))

_________________________________________________________________________________________________________________________________________
Full output:
_________________________________________________________________________________________________________________________________________
TypeError                                 Traceback (most recent call last)
Cell In[4], line 12
      9 microanim.add_label('A', label_font_size=30)
     10 microanim.add_time_stamp('T', 10, location='lower left', timestamp_size=20)
---> 12 microanim.save_movie(os.path.join(outfolder, os.path.split(file)[1][:-4] + '_composit.avi'))

File ~\Anaconda3\envs\image_anal\lib\site-packages\microfilm\microanim.py:207, in Microanim.save_movie(self, movie_name, fps, quality, format)
    206 def save_movie(self, movie_name, fps=20, quality=5, format=None):
--> 207     save_movie(self, movie_name, fps=fps, quality=quality, format=format)

File ~\Anaconda3\envs\image_anal\lib\site-packages\microfilm\microanim.py:458, in save_movie(anim_object, movie_name, fps, quality, format)
    456     w,h = map(int, anim_object.fig.canvas.renderer.get_canvas_width_height())
    457     buf.shape = (h, w, 3)
--> 458     writer.append_data(buf)
    460 writer.close()

File ~\Anaconda3\envs\image_anal\lib\site-packages\imageio\v2.py:226, in LegacyWriter.append_data(self, im, meta)
    214     warnings.warn(
    215         "V3 Plugins currently don't have a uniform way to"
    216         " write metadata, so any metadata is ignored."
    217     )
    219 # total_meta = dict()
    220 # if meta is None:
    221 #     meta = {}
    222 # if hasattr(im, "meta") and isinstance(im.meta, dict):
    223 #     total_meta.update(im.meta)
    224 # total_meta.update(meta)
--> 226 return self.instance.write(im, **self.write_args)

File ~\Anaconda3\envs\image_anal\lib\site-packages\imageio\plugins\tifffile_v3.py:224, in TifffilePlugin.write(self, ndimage, is_batch, **kwargs)
    221     ndimage = np.asarray(ndimage)[None, :]
    223 for image in ndimage:
--> 224     self._fh.write(image, **kwargs)
    226 if self._request._uri_type == URI_BYTES:
    227     self._fh.close()

TypeError: write() got an unexpected keyword argument 'fps'

**Comment by guiwitz** [comment]
I don't know why imageio defaults to using the tifffile plugin to write a movie as the plugin does not handle movies. I think it makes this error because you don't have the correct movie writer plugin installed. Normally this is ffmpeg. It should get installed out of the box with microfilm but apparently this doesn't work for Mac M1. Are you on such an OS? If yes you can try to install ffmpeg manually:
```conda install ffmpeg -c conda-forge```
Let me know if that works!

**Comment by puentene** [comment]
Thanks for your quick reply. It was indeed the error.
installing ffmpeg via 
pip install ffmpeg 
or
conda install ffmpeg -c conda-forge
did not solve the problem but using 
pip install imageio-ffmpeg
worked out for me.
Thanks for the help!

**Comment by guiwitz** [comment]
Great to know that if works for you @puentene ! FYI, if you need to re-install in the future ```pip install "microfilm[animation]"``` should install ```imageio-ffmpeg``` automatically (but as mentioned on M1/M2 ffmpeg needs to be installed in addition). I haven't touched the animation part of the package in a while, so don't hesitate to post issues if you encounter other problems.
