### ISSUE TITLE
Color-blind friendly default color maps

### ISSUE THREAD

**Issue by haesleinhuepf** [guiwitz/microfilm#9]
Hi @guiwitz ,

I just started playing with microfilm and so far, I love it. I'd just have a minor suggestion: The default color maps (red, green, blue) pretty much fit to what people know from ImageJ, which is cool. Anyway, in image analysis courses we tell people to not use the default LUTs in ImageJ, because these are not color-blind friendly. Hence, one could think of using matplotlib-like default color maps using blue-orange-green-magenta. Or, to remain similar to ImageJ, just replace red with magenta and blue with cyan.

I'm just thinking in writing. Feel free to ignore this suggestion.

Best,
Robert

**Comment by guiwitz** [comment]
Hi @haesleinhuepf,

you exactly reconstructed my own reasoning :wink: I hesitated between offering the default that people expect, and "forcing" the "right" solution on them. This is why in the examples in the docs I use cyan/magenta when not using the defaults. But retrospectively, I think you are right, we should use the "right" solution as default.

I personally don't like the blue/orange combination (purely for a question of personal taste), so I'm rather inclined to use cyan/magenta/yellow. I also think that's the combination I have seen most often in microscopy papers. Any further thought? If not I'll switch to that!

Cheers,
Guillaume

**Comment by haesleinhuepf** [comment]
> cyan/magenta/yellow. I also think that's the combination I have seen most often in microscopy papers. Any further thought? If not I'll switch to that!

That sounds perfect actually. If you use internally a default-lut-list ([this one?](https://github.com/guiwitz/microfilm/blob/master/microfilm/microplot.py#L127)), could you maybe expose it via the API? We could then retrieve it and use the same colormaps for plotting e.g. using matplotlib.

**Comment by haesleinhuepf** [comment]
Hi @guiwitz ,

yes, I thought of something like drawing a plot with the same colour. Also, it would be cool if we could reuse the colormap in napari, for example.

**Comment by guiwitz** [comment]
This is really old but for the sake of completeness: the colormaps used in a ```microim = Microimage()``` object are accessible via the ```microim.cmap_objects``` attribute. Also the latest release of microfilm includes now colormaps from the [cmap](https://cmap-docs.readthedocs.io/en/latest/) library making it easier to re-use colormaps across different libraries (Matplotlib, napari etc.)
